services:
  - type: web
    name: ai-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RENDER
        value: true
      - key: OPENAI_API_KEY
        sync: false # Ensures this comes from Render environment variables
    healthCheckPath: / 